### ISSUE TITLE
encode to memory instead of file

### ISSUE THREAD

**Issue by benjajaja** [orhun/sixel-rs#1]
From the docs, it only seems possible to use `set_output(&self, file: &Path) -> Status<()>` to write the sixel output to a file.

There should be a way to get the encoded data some way instead. Is it possible at all with the wrapped lib? There seems to be some reference to it: https://github.com/saitoha/libsixel/blob/master/include/sixel.h.in#L574

**Comment by benjajaja** [comment]
I have managed to get the bytes back here https://github.com/benjajaja/sixel-bytes/blob/master/src/lib.rs#L165 but there is no way to do this with the `Encoder`: it only takes file descriptors as output. It's either write to file or to stdout.

Would it make sense to merge that crate in here? Exposing some function like:

```rust
sixel-rs::sixel_string(
    bytes: &[u8],
    width: i32,
    height: i32,
    pixelformat: PixelFormat,
    method_for_diffuse: DiffusionMethod,
) -> Result<String, Error>
```

**Comment by pythops** [comment]
+1

Would be great to be able to save to a buffer

**Comment by orhun** [comment]
Hey, I would be happy to accept a PR to have this functionality. I will take a look at this myself in my free time but the idea makes sense to me.

> Would it make sense to merge that crate in here? Exposing some function like:

Yup!

Also, this crate needs more love so I created #3

**Comment by benjajaja** [comment]
I will try to merge sixel-bytes into this repo sometime.

Meanwhile https://github.com/mkrueger/icy_sixel has been written, which is not nearly as complete as libsixel, but is native and thus has no linker pitfalls.

**Comment by orhun** [comment]
Nice! Mentioned it in #4
